### PR TITLE
add lib.makeModule to convert default.nix packge funcs to drv-parts modules

### PR DESCRIPTION
**Pull request by DavHau**
This adds `lib.makeModule`, which can convert a default.nix from nixpkgs to a drv-parts module.
It tries to detect which of the default.nix arguments are flags and which are dependencies.
For the flags it creates nixos options, for the dependencies it expects them to be passed via `deps`.

It does not try to extract the arguments to mkDerivation crafted by the default.nix.
Instead it just let's the default.nix create the derivation, and then calls overrideAttrs on it to add our values.

Though there is a problem with this approach. The merging of the default.nix derivation args and the drv-parts args is happening inside the overrideAttrs call and invisible to the module system. This leads to problems (see code comments)

I'm not yet quite confident about that approach. Possibly you have some ideas @roberth.
Maybe I should not base this on the existing `./module/mkDerivation` module, but instead generate a module completely from scratch, by extracting the derivation attrs first, and using those as defaults for the options.

### CODE REVIEW

**Comment by roberth** [comment]
> Maybe I should not base this on the existing `./module/mkDerivation` module,

Isn't the goal to have `./module/mkDerivation` behavior?

> but instead generate a module completely from scratch, by extracting the derivation attrs first,

You can do this with the __expose thing from https://github.com/DavHau/drv-parts/issues/3#issuecomment-1344451235
That gives you the `mkDerivation` arguments that you can then translate to `config`.

On the input side of the package function, I'm not sure what to do. Maybe "give up" and declare `legacyArgs`, let `callPackage` fill them. You could modify `callPackage` (or `makeOverridable`) to give out the exact arguments it passes.
After all, a package function isn't really complete without its `callPackage` invocation.
This requires a change to Nixpkgs that I'm not sure we should want to have there, making `makeOverridable` leaky.
Maybe the input side of the package function should be kept simple; just an option for the `overrides` as in `pkg: overrides: pkg.override(_ignoredArg: overrides)`, to be used before doing the `__expose` trick to get the `mkDerivation` arguments.

<details><summary>leaky makeOverridable</summary>

```nix
  makeOverridable = f: origArgs:
    let
      result = f origArgs;

      # Creates a functor with the same arguments as f
      copyArgs = g: lib.setFunctionArgs g (lib.functionArgs f);
      # Changes the original arguments with (potentially a function that returns) a set of new attributes
      overrideWith = newArgs: origArgs // (if lib.isFunction newArgs then newArgs origArgs else newArgs);

      # Re-call the function but with different arguments
      overrideArgs = copyArgs (newArgs: makeOverridable f (overrideWith newArgs));
      # Change the result of the function call by applying g to it
      overrideResult = g: makeOverridable (copyArgs (args: g (f args))) origArgs;
    in
      if builtins.isAttrs result then
        result // {
          override = overrideArgs;
          overrideDerivation = fdrv: overrideResult (x: overrideDerivation x fdrv);
          ${if result ? overrideAttrs then "overrideAttrs" else null} = fdrv:
            overrideResult (x: x.overrideAttrs fdrv);
         #### *** NEW ***
          __makeOverridableArgs = origArgs;
        }
      else if lib.isFunction result then
        # Transform the result into a functor while propagating its arguments
        lib.setFunctionArgs result (lib.functionArgs result) // {
          override = overrideArgs;
          __makeOverridableArgs = origArgs;
        }
      else result;
```
</details>

I think this is ok as a migration shim, but it can't cover everything. If users want it to be as good as modules, they need to adopt modules. We'll have to manage expectations.

**Comment by alex-ameen** [comment]
The routines `apply`, `callWith`, and `callWithOv` here are likely useful.

I plan to PR these is Nixpkgs, essentially they split up `callPackage` into parts that can be used in isolation.

https://github.com/aakropotkin/ak-nix/blob/7242b7d7c49037700def339ea232d594b67dcd7c/lib/funk.nix#L292

**Comment by roberth** [comment]
I think an important question is do we want to convert called packages or package functions.

Called packages are great if you want to import from Nixpkgs. Having access to the real argument values will make it much more reliable.

Package functions may be desirable in non-Nixpkgs projects, that may not rely on the second `callPackage` argument as much. However, in non-Nixpkgs projects, I think "just doing the work" is much more feasible, and gives the best result; in other words, don't encourage people to write packages in the old style and expect them to work well as a modular package.

For incremental migration, I think users are helped equally well with any conversion function, regardless of the direction. Perhaps the opposite conversion is easier? If they can convert a package function to a module by hand (which is good; working toward the end goal), can we provide a function `callModulePackage` that emulates `callPackage` more closely? By providing `.override` and `.overrideAttrs`? Both can be implemented using `extendModules` and a function for auto-incrementing the priority of the config definitions that are in the argument. Roughly:

```nix
{ config, options, extendModules, ... }:

{
# aah I hate passthru. It's such a polished turd. "package attribute" is the right term.
# anyway, I think this gets the point across
config.passthru.overrideAttrs = f: 
  let attrs = f config;
       overrides =
         mapAttrs
           (k: v: mkOverride options.${k}.highestPrio v
                    # + recurse if `options.${k}` is not an option (but a node of the options tree)
            )
           attrs;
  in extendModules { modules = [ overrides ]; };
}
```

**Comment by DavHau** [comment]
> > Maybe I should not base this on the existing `./module/mkDerivation` module,
> 
> Isn't the goal to have `./module/mkDerivation` behavior?
> 
> > but instead generate a module completely from scratch, by extracting the derivation attrs first,
> 
> You can do this with the __expose thing from [#3 (comment)](https://github.com/DavHau/drv-parts/issues/3#issuecomment-1344451235) That gives you the `mkDerivation` arguments that you can then translate to `config`.

I had an issue with that: mapping the arguments from `__expose` to the drv-parts `mkDerivation` interface. The interface is different because we have `env` instead of the free-form style.

I tried programmatically matching the provided args against the known options of  `drv-parts`, but was running into infinite recursion. Also I'm not even sure how to retrieve to list of options properly. How would one do this?

Also I'm unsure if separating the `env` variables out was the right decision to begin with, because:
1. It's not clear what even counts as `env` variable and what not. Most of what is passed to mkDerivation is eventually exposed as an env variable. Should `buildInputs` be defined under `env` or not? Currently it is not.
1. It competes with the recently merged structuredAttrs. The upstream `structuredAttrs` likely did a different decision on where to draw the line between `env` and `top-level` args. I feel by introducing a custom subset of `structuredAttrs` features in drv-parts we might make migration between package declarations even harder. Maybe it's better to just enable upstream structuredAttrs by default? I haven't yet looked into it really, and cannot tell if this would be a good idea or not.
1. Even if we keep the custom `env` separation, it could be implemented as a separate module, while we also have a module supporting the free-form style. But then again, is it a good idea to have different interfaces at all?

> However, in non-Nixpkgs projects, I think "just doing the work" is much more feasible,

Maybe that's true, and we can spare us the hassle maintaining that compatibility module of the current PR.
The idea of providing override[Attrs] as a compatibility layer sounds interesting. I should experiment with this once I find some time.
Should `override` and `overrideAttrs` both just point to the same function, accepting the same arguments for simplification?

**Comment by roberth** [comment]
> Also I'm unsure if separating the `env` variables out was the right decision to begin with

structuredAttrs needs something like this, so it's not all bad. It may need to change, maybe?

> but was running into infinite recursion.

Did you try to generate options or config? If you generate options, you'll have infinite recursion, but values in `config` should be able to read from `options`.

> Should `override` and `overrideAttrs` both just point to the same function, accepting the same arguments for simplification?

I think `override` should only override the `deps` and perhaps some "flag" options if there's a good heuristic for that. Otherwise, putting those flags in `deps` is fine. Making it work is more important than making it pretty I think.
`overrideAttrs` should set the same things that the translation code already sets. It could probably reuse all that logic.

**Comment by AndersonTorres** [comment]
Hello! I have received a link on a Matrix discussion channel about this project, and I found it very interesting.

About tis PR: what is the idea of this pull request? Is it to make a wrapper around existing Nixpkgs codebase, or is it more akin to a nix-to-nix transpiler?

**Comment by DavHau** [comment]
@AndersonTorres The purpose of the current PR is to provide a wrapper for existing package declarations a la `default.nix` style, so that those definitions will be converted to drv-parts compatible modules on the fly.

That would mean that people would not be forced to go through refactoring a lot of code in order to use drv-parts.

Though, as Robert already pointed out, we could alternatively provide other means of backward compatibility. It's not quite clear yet what exactly to make of this PR. Currently I still think it can be valuable.

My main struggle was with implementation. Partly because the initial code base was not thought out well enough. Today I was working a lot on refactoring the current state (see recent commits on master branch). So I might continue working on the current PR in the near future.

**Comment by DavHau** [comment]
After refining some fundamentals, this now feels a lot cleaner.
The derivations created by converting default.nix functions to modules now have the same drv hashes as the originals from nixpkgs. There are a bunch of tests to ensure that which can be executed via:
`nix run .#tests-examples`.

I still want to get rid of the manual merging in overrideDrv though, to make this really nice

**Comment by AndersonTorres** [comment]
Given that line:

> For incremental migration, I think users are helped equally well with any conversion function, regardless of the direction. 

Should I suppose that the endgame is a complete migration?

**Comment by roberth** [comment]
I don't think you'd want to incur the complexity of both systems, but I may be wrong.

**Comment by AndersonTorres** [comment]
Good to know. It should become a _sprintable_, then!

(Indeed, I wanna test this on some packages I maintain.)

**Comment by DavHau** [comment]
I think this is ready now for final review.

I extended the makeModule function, so it extracts the mkDerivation arguments from the default.nix file, and then merges them in via a second evalModules.
That gets rid of the previously troublesome custom merge.

> > but was running into infinite recursion.
> 
> Did you try to generate options or config? If you generate options, you'll have infinite recursion, but values in `config` should be able to read from `options`.

I think the problem was, that the config contains inputs for the default.nix function and at the same time the result of the default.nix needs to be merged with the config. Probably not an issue once arguments are separated perfectly, but debugging it seemed annoying. Doing the merge via a separate evalModules feels cleaner.

**Pull request merged**
